format_version: 10
pipelines:
  my-test-app-pipeline:
    group: tomcatProductionConfig
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-936cdf3:
        git: git@github.com:skymaster-io/test-app.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - containerizing:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-image:
            timeout: 0
            environment_variables:
              someVar: something
            secure_variables:
              password: AES:NQVZ9wFuqHNLwuojKL2+cQ==:dbCI8LjtA0zCsW8sFf+PyQ==
            tasks:
            - exec:
                arguments:
                - build
                - .
                - -t
                - test-image
                command: docker
                run_if: passed
